---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
pkgload::load_all()
```

# audubon

<!-- badges: start -->
<!-- badges: end -->

> [ローマ字とひらがなを変換するやつ](https://github.com/yumetodo/romaji_kana_cvt_rust)

## Comparisons

### To Roman

```{r to_roman}
zipangu::str_conv_romanhira("でゅららら", "roman")
audubon::invert_to_roman("でゅららら")
zipangu::str_conv_romanhira("ゑぐざゐる", "roman")
audubon::invert_to_roman("ゑぐざゐる")
zipangu::str_conv_romanhira("じぇんつーぺんぎん", "roman")
audubon::invert_to_roman("じぇんつーぺんぎん")
zipangu::str_conv_romanhira("じぇんつうぺんぎん", "roman")
audubon::invert_to_roman("じぇんつうぺんぎん")
```

### To Hiragana

```{r to_kana}
zipangu::str_conv_romanhira("dhurarara", "hiragana")
audubon::invert_to_kana("dhurarara")
zipangu::str_conv_romanhira("weguzawyiru", "hiragana")
audubon::invert_to_kana("weguzawyiru")
zipangu::str_conv_romanhira("jent'upengin", "hiragana")
audubon::invert_to_kana("jent'upengin")
```

### Limitations

- カタカナや「ー」など、マップできない文字があると`NA_character`になる
- おそらくWindowsではデフォルトエンコーディングの影響で戻り値に「ゔ」が含まれると上手く変換されない


## License

BLS-1.0
