# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_audubon_wrappers", use_symbols = TRUE, package_name = "audubon")

#' @docType package
#' @usage NULL
#' @useDynLib audubon, .registration = TRUE
NULL

convert <- function(input) .Call(wrap__convert, input)

